#!/usr/bin/env bash
# view-setup.sh — one-shot setup for a camera/video:
#   1. draw the zones (1 = line, 2 = Mashgin POS, 3 = non-Mashgin; n = new contour; s = save; q = quit)
#   2. write a reusable run script to viewscripts/<video>.sh
#   3. calibrate busy bands -> calib/<video>.json (skip with --no-calibrate)
#   4. launch the pipeline + dashboard (unless --no-run)
#
# Usage:
#   ./view-setup.sh -v <video>                  # path, or a bare name found in videos/
#   ./view-setup.sh -v clip.mp4 --no-calibrate  # skip the calibration pass
#   ./view-setup.sh -v clip.mp4 --no-run --port 8050
set -euo pipefail
cd "$(dirname "$0")"

VIDEO="" ; RUN=1 ; PORT=8000 ; CALIBRATE=1

usage(){ sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    -v|--video)      VIDEO="${2:-}"; shift 2;;
    --no-run)        RUN=0; shift;;
    --no-calibrate)  CALIBRATE=0; shift;;
    --port)          PORT="${2:-}"; shift 2;;
    -h|--help)       usage; exit 0;;
    *) if [[ -z "$VIDEO" ]]; then VIDEO="$1"; shift; else echo "unknown arg: $1" >&2; exit 1; fi;;
  esac
done

[[ -n "$VIDEO" ]] || { echo "error: no video given (-v <video>)" >&2; usage; exit 1; }
# resolve: accept a full path, or a bare name living under videos/
if [[ ! -f "$VIDEO" && -f "videos/$VIDEO" ]]; then VIDEO="videos/$VIDEO"; fi
[[ -f "$VIDEO" ]] || { echo "error: video not found: $VIDEO" >&2; exit 1; }

STEM="$(basename "${VIDEO%.*}")"
ZONE="zones/${STEM}.json"
POS="zones/${STEM}_pos.json"
ALT="zones/${STEM}_alt.json"
CAL="calib/${STEM}.json"

echo "==> Zone setup for: $STEM"
echo "    keys:  1 = line   2 = Mashgin POS   3 = non-Mashgin   n = new contour   u = undo   c = clear   s = save   q = quit"
uv run python main.py --define-zone --source "$VIDEO"

[[ -f "$ZONE" ]] || { echo "error: no line zone was saved ($ZONE) — re-run and press 's' after drawing." >&2; exit 1; }
echo "==> saved: line$( [[ -f "$POS" ]] && echo ' + Mashgin POS' )$( [[ -f "$ALT" ]] && echo ' + non-Mashgin' )"

mkdir -p viewscripts runs
SCRIPT="viewscripts/${STEM}.sh"
{
  echo '#!/usr/bin/env bash'
  echo '# auto-generated by view-setup.sh — runs storePose for this camera. Extra flags pass through.'
  echo 'set -euo pipefail'
  echo 'cd "$(dirname "$0")/.."'
  echo ''
  printf 'CALIB=%q\n' "$CAL"
  echo 'EXTRA=()'
  echo '# pick up busy calibration if it exists, unless STOREPOSE_NO_CALIB is set'
  echo '# (the launcher sets that env var when you toggle calib off)'
  echo '[[ -z "${STOREPOSE_NO_CALIB:-}" && -f "$CALIB" ]] && EXTRA+=(--calib "$CALIB")'
  echo ''
  printf 'uv run python main.py --source %q --zone %q' "$VIDEO" "$ZONE"
  [[ -f "$POS" ]] && printf ' --pos-zone %q' "$POS"
  [[ -f "$ALT" ]] && printf ' --alt-zone %q' "$ALT"
  printf ' --busy --wait-log %q --busy-log %q --dashboard-port %q "${EXTRA[@]+"${EXTRA[@]}"}" "$@"\n' \
         "runs/${STEM}_waits.csv" "runs/${STEM}_busy.csv" "$PORT"
} > "$SCRIPT"
chmod +x "$SCRIPT"
echo "==> wrote $SCRIPT"

# Calibrate the busy bands from this clip's occupancy so calib/<stem>.json exists
# from the first run (the viewscript and TUI pick it up automatically). Headless;
# uses the same zones the run does. Non-fatal — a run works without bands.
if [[ "$CALIBRATE" -eq 1 ]]; then
  echo "==> calibrating busy bands (headless, full-clip scan) -> $CAL"
  CAL_ARGS=(--calibrate --source "$VIDEO" --zone "$ZONE")
  [[ -f "$POS" ]] && CAL_ARGS+=(--pos-zone "$POS")
  [[ -f "$ALT" ]] && CAL_ARGS+=(--alt-zone "$ALT")
  if uv run python main.py "${CAL_ARGS[@]}"; then
    echo "==> wrote $CAL"
  else
    echo "warning: calibration failed; continuing without bands (re-run with --calibrate later)" >&2
  fi
else
  echo "==> skipping calibration (--no-calibrate); calib/<stem>.json not created"
fi

if [[ "$RUN" -eq 1 ]]; then
  echo "==> launching (dashboard: http://127.0.0.1:${PORT}/) — press q/Esc in the window to quit"
  exec "$SCRIPT"
else
  echo "==> done. run later with:  ./video-run.sh   (or  $SCRIPT)"
fi
